### ISSUE TITLE
problems with generating trajectories

### ISSUE THREAD

**Issue by marselomeri** [Airspace-Encounter-Models/em-model-unmanned-recreational#3]
Hi, 
I am trying to use the code to generate several trajectories, I followed the instructions step by step, but I end up with the following error:

I am running the code on Windows and using the latest stable version of Julia 1.6.3. 

![image](https://user-images.githubusercontent.com/41054948/142407945-0c57e406-2201-4d94-9c55-d5ad5304e21a.png)

**Comment by aweinert-MIT** [comment]
The code was developed using Julia1.1 while this error is occurring in a newer version of 1.6.3. Have you tried to replicating the bug using [v1.1.1 (May 16, 2019)](https://julialang.org/downloads/oldreleases/)?

**Comment by marselomeri** [comment]
Hello, sorry for the late reply! 
I changed Julia's version to 1.1.1 and still have the same error when running "generate_trajectory_file(""). 
I will have a detailed look in the code files and will let you know as soon as possible. Any tips or suggestion is more than welcomed!

**Comment by aadeabreu** [comment]
The code works properly for me in Julia 1.6.1. You seem to have some kind of warning before you include `HobbyDroneInterface`. You might want to check that `BayesNets` package was installed correctly. See below for the output I get.
![Capture](https://user-images.githubusercontent.com/87670274/143874084-1047e664-b817-4c7e-8374-1beed78399be.JPG)

**Comment by Wh0DKnee** [comment]
I have the same issue as @marselomeri. My output looks identical to yours for the first two commands @aadeabreu except that the Pkg.jl number in the warnings is 595. When I run generate_trajectory_file, I get the exact same error as @marselomeri.

**Comment by aweinert-MIT** [comment]
> I have the same issue as @marselomeri. My output looks identical to yours for the first two commands @aadeabreu except that the Pkg.jl number in the warnings is 595. When I run generate_trajectory_file, I get the exact same error as @marselomeri.

@Wh0DKnee, to reduce potential confusion, what version of Julia are you using?

**Comment by aweinert-MIT** [comment]
I've created the [issue-3 branch](https://github.com/Airspace-Encounter-Models/em-model-unmanned-recreational/tree/issue-3) for development related to this issue.

**Comment by Wh0DKnee** [comment]
> > I have the same issue as @marselomeri. My output looks identical to yours for the first two commands @aadeabreu except that the Pkg.jl number in the warnings is 595. When I run generate_trajectory_file, I get the exact same error as @marselomeri.
> 
> @Wh0DKnee, to reduce potential confusion, what version of Julia are you using?

I am using Julia 1.7.0, so not exactly the same as @marselomeri , but the error is identical.

**Comment by aweinert-MIT** [comment]
@marselomeri are you still experiencing this bug?

**Comment by Wh0DKnee** [comment]
@aweinert-MIT I still am experiencing it for what it's worth.

**Comment by aweinert-MIT** [comment]
Yeah, we won't close this issue until the bug is resolved. We have a roadmap scheduled to be released this month, so that is currently taking priority

**Comment by marselomeri** [comment]
Hello everyone, there was a small mistake with the file CreateHobbyDroneTrajectories.jl. In the line 195, you should substitute it with if key!=: potential. You may see it attached in the picture.  Also, I was reading the thesis written by Eric R. Muller to understand what kind of coordinate frame he uses in his simulations. In my opinion he converts lat/lon/alt into NED reference frame, but I am not sure, since he doesn't specifically say that in his thesis.  I am attaching a figure from pg. 95. of a flight profile, maybe you can give more insight into the matter. Thanks!
![bug_line195_CreateHobbyDroneTrajetories jl](https://user-images.githubusercontent.com/41054948/160427281-d963bfdb-7634-4fa1-adbd-86d42538a4da.png)
![North-South East-West Coordinate Frame](https://user-images.githubusercontent.com/41054948/160427321-b21ab3dc-0b98-4b53-bdb4-8ab4c1551fcf.png)

**Comment by aweinert-MIT** [comment]
@marselomeri To confirm does updating line 195 with `key!=: potential` resolve the issue reported originally or is this a separate issue?

**Comment by marselomeri** [comment]
@aweinert-MIT  Yes, making the change fixes the issue I have reported originally, sorry for the confusion.

**Comment by aweinert-MIT** [comment]
Great! Do you want to create a pull request with the change to resolve the issue?

**Comment by marselomeri** [comment]
I think you could just update the file; it is not worth making a pull request! In the other hand, should I post the question and the mission profile about the coordinate system in the other issue ( I just realized that there are two separate issues).

**Comment by aweinert-MIT** [comment]
An advantage of a pull request is that it gives you credit for the change. I can make the change if you like still. 

Yes, please create a separate issue about coordinate system question, as this issue will be closed once we make the update.

**Comment by marselomeri** [comment]
It is fine by me. Thanks! I will ask the question in the other issue.

**Comment by aweinert-MIT** [comment]
Please review issue #1 before creating a new issue about your question. There could be overlap and you may want to just expand #1

**Comment by aweinert-MIT** [comment]
@marselomeri , can you please pull dev-issue-3 branch and confirm that pull request #4  resolves the issue?

**Comment by marselomeri** [comment]
@aweinert-MIT  sorry for the late reply! I can confirm it works perfectly, all the functions: generate multiple trajectories and with different flight time. I am testing it with Julia V1.1.1 and Ubuntu 20.04.

**Comment by aweinert-MIT** [comment]
Closing issue because pull request #4 resolved this bug
